import React,{useMemo,useState} from 'react';
import {Plus,Edit3,Trash2,Image as ImageIcon,Tags,ChevronDown,ChevronLeft} from 'lucide-react';
import {api,money} from '../../lib/utils';
import {useProgress} from '../../context/ProgressContext';
import Editor from './Editor';

export default function Items({data,refresh}){
  const {run}=useProgress();
  const [tab,setTab]=useState('item');
  const [editing,setEditing]=useState(null);
  const [catEditing,setCatEditing]=useState(null);
  const [catName,setCatName]=useState('');
  const [expanded,setExpanded]=useState(null);
  const [error,setError]=useState('');
  const categories=Array.isArray(data.categories)?data.categories:[];
  const items=Array.isArray(data.items)?data.items:[];
  const offers=Array.isArray(data.offers)?data.offers:[];
  const countFor=c=>items.filter(i=>Number(i.category_id)===Number(c.id)).length;
  const save=async form=>{setError('');try{const isItem=tab==='item';const path=isItem?'/admin/items':'/admin/offers';const body=isItem?{...form,price:Number(form.price),category_id:form.category_id||null,sort_order:Number(form.sort_order)||0,allergens:form.allergens||'',options_json:JSON.stringify(Array.isArray(form.options)?form.options:[])}:{...form,price:Number(form.price),sort_order:Number(form.sort_order)||0};await run(editing?.id?'جاري حفظ التعديل…':'جاري إضافة العنصر…',()=>api(editing?.id?path+'/'+editing.id:path,{method:editing?.id?'PUT':'POST',body:JSON.stringify(body)}));setEditing(null);await refresh()}catch(e){setError(e.message)}};
  const deleteThing=async x=>{if(!confirm(`هل أنت متأكد من حذف ${tab==='item'?'الصنف':'العرض'}؟`))return;try{await run('جاري حذف العنصر…',()=>api((tab==='item'?'/admin/items/':'/admin/offers/')+x.id,{method:'DELETE'}));await refresh()}catch(e){setError(e.message)}};
  const saveCat=async()=>{if(!catName.trim())return;try{await run(catEditing?.id?'جاري حفظ التصنيف…':'جاري إضافة التصنيف…',()=>api(catEditing?.id?'/admin/categories/'+catEditing.id:'/admin/categories',{method:catEditing?.id?'PUT':'POST',body:JSON.stringify({name:catName.trim()})}));setCatEditing(null);setCatName('');await refresh()}catch(e){setError(e.message)}};
  const deleteCat=async c=>{if(!confirm(`حذف التصنيف «${c.name}»؟ الأصناف التابعة له ستبقى بدون تصنيف.`))return;try{await run('جاري حذف التصنيف…',()=>api('/admin/categories/'+c.id,{method:'DELETE'}));if(expanded===c.id)setExpanded(null);await refresh()}catch(e){setError(e.message)}};
  const openAddItem=(categoryId='')=>{setTab('item');setEditing({category_id:categoryId||categories[0]?.id||'',name:'',description:'',price:'',image:'',available:true,featured:false,sort_order:items.length+1,allergens:'',options:[]})};
  const renderProduct=(x,isItem=true)=> <div className="admin-category-product" key={`${isItem?'item':'offer'}-${x.id}`}><div className="admin-category-product-main">{x.image?<img src={x.image} alt=""/>:<div className="admin-category-product-placeholder"><ImageIcon size={20}/></div>}<div><b>{isItem?x.name:x.title}</b><small>{x.description||'بدون وصف'}</small>{isItem&&<span>{money(x.price,data.settings.currency)}</span>}{!isItem&&<span>{money(x.price,data.settings.currency)}</span>}</div></div><div className="admin-category-product-actions"><button className="icon-btn" onClick={()=>{setTab(isItem?'item':'offer');setEditing(x)}} title="تعديل"><Edit3 size={16}/></button><button className="icon-btn danger" onClick={()=>deleteThing(x)} title="حذف"><Trash2 size={16}/></button></div></div>;
  return <section className="panel items-admin-panel">
    <div className="admin-tabs items-tabs" role="tablist" aria-label="إدارة الأصناف"><button className={tab==='item'?'active':''} onClick={()=>setTab('item')}>الأصناف</button><button className={tab==='offer'?'active':''} onClick={()=>setTab('offer')}>العروض</button><button className={tab==='category'?'active':''} onClick={()=>setTab('category')}><Tags size={16}/> التصنيفات</button></div>
    {error&&<div className="error admin-error">{error}</div>}
    {tab!=='category'&&<div className="toolbar"><div><h2 className="panel-title-inline">{tab==='item'?'الأصناف':'العروض'}</h2><span className="muted">{tab==='item'?items.length:offers.length} عنصر</span></div><button className="btn primary" onClick={()=>openAddItem()}><Plus/> إضافة {tab==='item'?'صنف':'عرض'}</button></div>}
    {editing&&<div className="modal-bg admin-editor-overlay"><div className="modal admin-editor-modal"><Editor type={tab==='item'?'item':'offer'} value={editing} categories={categories} onCancel={()=>setEditing(null)} onSave={save}/></div></div>}
    {tab==='category'?<>
      <div className="admin-section-title"><div><Tags size={18}/><div><span className="eyebrow">تنظيم القائمة</span><h2>التصنيفات</h2></div></div><button className="btn primary" onClick={()=>{setCatEditing({});setCatName('')}}><Plus size={17}/> إضافة تصنيف</button></div>
      <div className="category-admin-table"><div className="category-admin-table-head"><span>التصنيف</span><span>عدد الأصناف</span><span>الإجراءات</span></div>{categories.map(c=>{const catItems=items.filter(i=>Number(i.category_id)===Number(c.id));const open=expanded===c.id;return <div className={`category-admin-row ${open?'expanded':''}`} key={c.id}><div className="category-admin-summary" onClick={()=>setExpanded(open?null:c.id)}><div className="category-admin-name"><button className="category-expand-btn" aria-label={open?'طي التصنيف':'توسيع التصنيف'}>{open?<ChevronDown size={17}/>:<ChevronLeft size={17}/>}</button><strong>{c.name}</strong></div><span className="category-count">{catItems.length}</span><div className="category-admin-actions"><button className="icon-btn" onClick={e=>{e.stopPropagation();setCatEditing(c);setCatName(c.name)}}><Edit3 size={16}/></button><button className="icon-btn danger" onClick={e=>{e.stopPropagation();deleteCat(c)}}><Trash2 size={16}/></button><button className="btn ghost small-btn" onClick={e=>{e.stopPropagation();openAddItem(c.id)}}><Plus size={14}/> إضافة صنف</button></div></div>{open&&<div className="category-expanded-content"><div className="category-expanded-head"><span>الأصناف داخل التصنيف</span><b>{catItems.length}</b></div>{catItems.length?catItems.map(i=>renderProduct(i,true)):<div className="category-empty">لا توجد أصناف في هذا التصنيف.</div>}</div>}</div>})}</div>
      {catEditing&&<div className="category-editor"><input autoFocus placeholder="اسم التصنيف" value={catName} onChange={e=>setCatName(e.target.value)}/><button className="btn primary" onClick={saveCat}>حفظ</button><button className="btn ghost" onClick={()=>setCatEditing(null)}>إلغاء</button></div>}
    </>:<div className="admin-grid">{(tab==='item'?items:offers).map(x=> <div className="admin-card admin-product-card" key={x.id}>{x.image?<img className="admin-card-image" src={x.image} alt={tab==='item'?x.name:x.title}/>:<div className="admin-image-placeholder"><ImageIcon size={28}/><span>لا توجد صورة</span></div>}<div className="card-top"><span className="status-dot">{tab==='item'?(x.available?'متاح':'مخفي'):(x.active?'فعال':'متوقف')}</span><div className="card-actions"><button className="icon-btn" onClick={()=>setEditing(x)}><Edit3 size={17}/></button><button className="icon-btn danger" onClick={()=>deleteThing(x)}><Trash2 size={17}/></button></div></div><div className="admin-product-info"><h3>{tab==='item'?x.name:x.title}</h3>{tab==='item'&&<small className="category-name">{categories.find(c=>Number(c.id)===Number(x.category_id))?.name||'بدون تصنيف'}</small>}<p>{x.description}</p><strong>{money(x.price,data.settings.currency)}</strong></div></div>)}</div>}
  </section>
}
