import React,{useEffect,useState} from 'react';
import {Plus,Minus,Trash2,X,MapPin,Gift,UserRound} from 'lucide-react';
import {api,money,moneyInWords} from '../../lib/utils';
import {useProgress} from '../../context/ProgressContext';
export default function CartModal({cart,setCart,total,settings,customer,onClose,onSent}){
  const currency=settings?.currency||'ل.ل'; const defaultAddress=customer?.addresses?.find(a=>a.is_default)?.address||'';
  const [form,setForm]=useState({customerName:customer?.user?.name||'',customerPhone:customer?.user?.phone||'',address:defaultAddress,notes:'',couponCode:'',deliveryZoneId:'',deliveryFee:0,loyaltyPoints:0});
  const [busy,setBusy]=useState(false),[err,setErr]=useState(''),[discount,setDiscount]=useState(0),[couponMsg,setCouponMsg]=useState(''),[zones,setZones]=useState([]),[loyaltyInfo,setLoyaltyInfo]=useState(null);
  useEffect(()=>{api('/public/delivery-zones').then(r=>setZones(r.zones||[])).catch(()=>{})},[]);
  useEffect(()=>{setForm(f=>({...f,customerName:customer?.user?.name||'',customerPhone:customer?.user?.phone||'',address:customer?.addresses?.find(a=>a.is_default)?.address||f.address||'',deliveryZoneId:'',deliveryFee:0,loyaltyPoints:0}));setLoyaltyInfo(null)},[customer]);
  const {run}=useProgress();
  const selectedZone=zones.find(z=>String(z.id)===String(form.deliveryZoneId));
  const afterCoupon=Math.max(0,total-discount); const pointValue=Math.max(1,Number(settings?.loyaltyPointValue||1000)); const minRedeem=Math.max(0,Number(settings?.loyaltyMinRedeem||10)); const maxPercent=Math.min(100,Math.max(0,Number(settings?.loyaltyMaxRedeemPercent||50))); const maxRedeem=Math.min(Number(customer?.points||0),Math.floor(Math.min(afterCoupon,afterCoupon*maxPercent/100)/pointValue)); const loyaltyDiscount=Math.min(maxRedeem,Math.max(0,Number(form.loyaltyPoints||0)))*pointValue; const finalPreview=Math.max(0,afterCoupon-loyaltyDiscount)+Number(form.deliveryFee||0);
  const submit=async e=>{e.preventDefault();setBusy(true);setErr('');try{const r=await run('جاري إرسال الطلب…',()=>api('/orders',{method:'POST',body:JSON.stringify({...form,deliveryZoneId:form.deliveryZoneId||null,deliveryFee:Number(form.deliveryFee||0),loyaltyPoints:Math.floor(Number(form.loyaltyPoints||0)),items:cart})}));onSent(r)}catch(e){setErr(e.message)}finally{setBusy(false)}};
  const applyCoupon=async()=>{const code=String(form.couponCode||'').trim();if(!code){setDiscount(0);setCouponMsg('يرجى إدخال كود الخصم');return}if(!Number.isFinite(Number(total))||Number(total)<=0){setDiscount(0);setCouponMsg('لا يمكن تطبيق كود الخصم على سلة فارغة');return}setCouponMsg('جاري التحقق…');try{const r=await api('/public/coupon/validate',{method:'POST',body:JSON.stringify({code,subtotal:Number(total)})});setDiscount(Number(r.discount||0));setCouponMsg(r.message||'تم تطبيق الخصم')}catch(e){setDiscount(0);setCouponMsg(e.message||'تعذر التحقق من كود الخصم')}};
  return <div className="modal-bg"><div className="modal cart-modal"><button className="close" onClick={onClose}><X/></button><h2>السلة وتأكيد الطلب</h2><form onSubmit={submit}><div className="cart-layout">
    <section className="cart-items-column"><div className="cart-column-head"><div><span className="eyebrow">طلبك</span><h3>الأصناف المطلوبة</h3></div><span className="cart-items-count">{cart.reduce((a,x)=>a+x.quantity,0)} صنف</span></div><div className="cart-lines">{cart.map(x=>{const key=x.cartKey||x.itemId;return <div className="cart-line cart-line-large" key={key}><div className="cart-line-info"><b>{x.name}</b>{x.options?.length?<small>الخيارات: {x.options.join('، ')}</small>:null}<small>{money(x.price,currency)} للصنف</small></div><div className="qty qty-large"><button type="button" aria-label="إنقاص الكمية" onClick={()=>setCart(c=>c.map(y=>(y.cartKey||y.itemId)===key?{...y,quantity:y.quantity-1}:y).filter(y=>y.quantity>0))}><Minus size={17}/></button><strong>{x.quantity}</strong><button type="button" aria-label="زيادة الكمية" onClick={()=>setCart(c=>c.map(y=>(y.cartKey||y.itemId)===key?{...y,quantity:y.quantity+1}:y))}><Plus size={17}/></button></div><strong className="cart-line-subtotal">{money(x.price*x.quantity,currency)}</strong></div>})}</div>{!cart.length&&<div className="empty-state">السلة فارغة.</div>}</section>
    <section className="cart-details-column"><div className="checkout-section"><div className="checkout-section-head"><span className="eyebrow">الخصم</span><h3>كود الخصم</h3></div><div className="coupon-row"><input placeholder="أدخل كود الخصم" value={form.couponCode} onChange={e=>{setForm({...form,couponCode:e.target.value.toUpperCase()});setCouponMsg('')}}/><button type="button" className="btn ghost" onClick={applyCoupon}>تطبيق</button></div>{couponMsg&&<small className={discount?'coupon-ok':'error'}>{couponMsg}</small>}</div>
      <div className="checkout-section"><div className="checkout-section-head"><span className="eyebrow">الاستلام</span><h3>طريقة الاستلام</h3></div><select value={form.deliveryZoneId} onChange={e=>{const zoneId=e.target.value;const z=zones.find(x=>String(x.id)===String(zoneId));setForm(f=>({...f,deliveryZoneId:zoneId,deliveryFee:z?Number(z.fee):0}))}}><option value="">استلام من الفرنية</option>{zones.map(z=><option key={z.id} value={z.id}>{z.name} — رسم التوصيل {money(z.fee,currency)}</option>)}</select>{selectedZone&&<div className="selected-delivery-zone"><MapPin size={16}/><span>منطقة التوصيل المختارة: <b>{selectedZone.name}</b></span><strong>{money(selectedZone.fee,currency)}</strong></div>}</div>
      {customer && settings?.loyaltyEnabled !== false && (
        <div className="checkout-section loyalty-checkout-section">
          <div className="checkout-section-head"><span className="eyebrow">الولاء</span><h3>استخدام نقاط الولاء</h3></div>
          <div className="loyalty-balance-row">
            <span>رصيدك: <b>{Number(customer.points || 0).toLocaleString('ar-LB-u-nu-latn')} نقطة</b></span>
            <span>{pointValue.toLocaleString('ar-LB-u-nu-latn')} {currency} / نقطة</span>
          </div>
          {maxRedeem > 0 ? (
            <div className="loyalty-input-area">
              <input className="loyalty-points-input" type="number" min="0" max={maxRedeem} step="1" placeholder={`أدخل النقاط (الحد ${maxRedeem})`} value={form.loyaltyPoints || ''} onChange={e => setForm({...form, loyaltyPoints: Math.min(maxRedeem, Math.max(0, Math.floor(Number(e.target.value || 0))))})} />
              <small className="loyalty-help">الحد الأدنى للاستخدام: {minRedeem} نقطة. يمكنك استخدام حتى {maxPercent}% من قيمة المنتجات بعد الخصم.</small>
              {loyaltyDiscount > 0 && <div className="loyalty-discount-note">خصم النقاط: {money(loyaltyDiscount, currency)}</div>}
            </div>
          ) : (
            <small className="loyalty-help">لا يمكن استخدام النقاط على هذا الطلب حالياً.</small>
          )}
        </div>
      )}
      <div className="checkout-section"><div className="checkout-section-head"><span className="eyebrow">بيانات الزبون</span><h3>معلومات الزبون</h3></div>{customer?<div className="checkout-customer-badge"><UserRound size={17}/><span>الطلب مرتبط بحساب <b>{customer.user.name}</b></span></div>:<div className="checkout-customer-badge"><UserRound size={17}/><span>أكمل بياناتك لإرسال الطلب</span></div>}<input required placeholder="الاسم" value={form.customerName} readOnly={!!customer} onChange={e=>setForm({...form,customerName:e.target.value})}/><input required placeholder="رقم الهاتف" value={form.customerPhone} readOnly={!!customer} onChange={e=>setForm({...form,customerPhone:e.target.value})}/>{customer?.addresses?.length?<select value={form.address} onChange={e=>setForm({...form,address:e.target.value})}><option value="">اختر عنواناً محفوظاً</option>{customer.addresses.map(a=><option key={a.id} value={a.address}>{a.label} — {a.address}</option>)}</select>:null}<input required placeholder="العنوان / المنطقة" value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/><textarea placeholder="ملاحظات على الطلب" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></div>
    </section></div><div className="cart-bottom"><div className="cart-price-breakdown"><div><span>المجموع الفرعي</span><b>{money(total,currency)}</b></div>{discount>0&&<div><span>خصم الكوبون</span><b>- {money(discount,currency)}</b></div>}{loyaltyDiscount>0&&<div><span>خصم نقاط الولاء</span><b>- {money(loyaltyDiscount,currency)}</b></div>}{Number(form.deliveryFee||0)>0&&<div><span>التوصيل</span><b>+ {money(form.deliveryFee,currency)}</b></div>}</div><div className="total cart-total"><span>الإجمالي</span><div className="total-values"><b>{money(finalPreview,currency)}</b><small>{moneyInWords(finalPreview,currency)}</small></div></div>{err&&<div className="error cart-submit-error">{err}</div>}<button type="submit" disabled={busy||!cart.length} className="btn primary cart-submit-btn">{busy?'جاري إرسال الطلب…':'إرسال الطلب'}</button></div></form></div></div>;
}
